### ISSUE TITLE
1

### ISSUE THREAD

**Issue by lmcmceo** [tdlight-team/tdlight#1]
with title

**Comment by lmcmceo** [comment]
and tdlight-java use libtdjni-linux-x86_64.so.1.6.9 ?

**Comment by cavallium** [comment]
TDLight Java already includes the tdjni libraries for each OS and architecture.
I Can't release the standalone .dll for windows but you can build it following tdlib build instructions: https://tdlib.github.io/td/build.html

**Comment by lmcmceo** [comment]
![image](https://user-images.githubusercontent.com/71498780/97803266-6f9f0f80-1c62-11eb-9193-f0a10e98ff62.png)
I mean when I run example, it show exception, I think it need tdjni.dll
