### ISSUE TITLE
sigabrt

### ISSUE THREAD

**Issue by andrew-ld** [tdlight-team/tdlight#14]
/version-tdlight-4.171.59-3.2.54/tdjni/tdjni.so(_ZN2td11PollManager22on_update_poll_timeoutENS_6PollIdE+0x1b1)[0x7f6f873fcb45]

/version-tdlight-4.171.59-3.2.54/tdjni/tdjni.so(_ZN2td9Scheduler8do_eventEPNS_9ActorInfoEONS_5EventE+0x216)[0x7f6f8766225c]

/version-tdlight-4.171.59-3.2.54/tdjni/tdjni.so(_ZN2td9Scheduler13flush_mailboxIPFvPNS_9ActorInfoEEPFNS_5EventEvEEEvS3_RKT_RKT0_+0xba)[0x7f6f876647ba]

**Comment by giuseppeM99** [comment]
i like this issue
