### ISSUE TITLE
GPlv3 license violation in one of the introduced libraries

### ISSUE THREAD

**Issue by tdlua** [tdlight-team/tdlight#19]
Hello sir, I have contacted you with permission from [giuseppeM99](https://github.com/giuseppeM99).

In the "[Using TDLib in Lua projects](https://github.com/tdlight-team/tdlight/blob/master/example/README.md#using-tdlib-in-lua-projects)", which you quoted it from [tdlib's github](https://github.com/tdlib/td/blob/master/example/README.md#lua), among the list of Lua libraries there is one library called [luagram ](https://github.com/Luagram/LuagramProject)and it's based on [tdlua](https://github.com/giuseppeM99/tdlua), but it violated GPLv3 license because:
1) They stole [giuseppeM99](https://github.com/giuseppeM99)'s code.
2) They edited the code a bit to remove any trace of [tdlua](https://github.com/giuseppeM99/tdlua), and they renamed [tdlua ](https://github.com/giuseppeM99/tdlua)to [luagram](https://github.com/Luagram/LuagramProject).
The developer knows this because he had to de-compile the binary they gave and he checked that the functions name are the same as in [tdlua ](https://github.com/giuseppeM99/tdlua) and that they just changed the prefix **tdlua** with **luagram**, eg the function _tdlua_send_ has been renamed to _luagram_send_.
3) Then they uploaded just the binary under their name and they didn't mention [giuseppeM99 ](https://github.com/giuseppeM99) anywhere and they didn't disclose the source code of their project too.

I raised an issue on their github page a few hours ago, **they currently deleted the repo**.
I'm kindly asking you to remove _luagram_ from the [readme file](https://github.com/tdlight-team/tdlight/blob/master/example/README.md#lua) until they fix the GPLv3 violations.

**Comment by tdlua** [comment]
Given that the link doesn't work anymore, it can be safely removed.

_Originally posted by @levlam in https://github.com/tdlib/td/issues/1568#issuecomment-859132783_

**Comment by cavallium** [comment]
Fixed
