### ISSUE TITLE
如何设置代理服务器

### ISSUE THREAD

**Issue by suqiernb** [tdlight-team/tdlight#20]
tdlib中怎样设置一个代理服务器, 某些地区无法连接到telegram的服务器

**Comment by MarcoBuster** [comment]
Could you please write in English? We don't speak your language.

**Comment by suqiernb** [comment]
How do I use a proxy server

**Comment by cavallium** [comment]
Use addProxy:
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1add_proxy.html
