### ISSUE TITLE
Error 522 - Maven could not get resource

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [tdlight-team/tdlight#21]
https://mvn.mchv.eu/repository/mchv/it/tdlight/tdlight-java/3.171.43/tdlight-java-3.171.43.pom

It seems your maven has fallen, I can't download the dependency.
![Screenshot_20210725_160439](https://user-images.githubusercontent.com/44233829/126900096-e634746f-35d5-4604-bf23-4f8de38e6d0a.png)

**Comment by cavallium** [comment]
Fixed
