### ISSUE TITLE
Not receiving updateAccessHash after 1.7.9.

### ISSUE THREAD

**Issue by AYMENJD** [tdlight-team/tdlight#26]

**Comment by cavallium** [comment]
Are you sure? Did you set receive_access_hashes to true?

**Comment by cavallium** [comment]
Do you have the chat info db disabled?

**Comment by AYMENJD** [comment]
Hmm, i found this error:
```
{'@type': 'error', 'code': 400, 'message': 'Failed to parse JSON object as TDLib request: Unknown class "updateOption"'}

```
The sent data:
```
{'@type': 'updateOption', 'name': 'receive_access_hashes', 'value': {'@type': 'optionValueBoolean', 'value': True}}

```

**Comment by AYMENJD** [comment]
> 
> 
> Do you have the chat info db disabled?

All databases enabled.

**Comment by cavallium** [comment]
> Hmm, i found this error:
> 
> ```
> {'@type': 'error', 'code': 400, 'message': 'Failed to parse JSON object as TDLib request: Unknown class "updateOption"'}
> ```
> 
> The sent data:
> 
> ```
> {'@type': 'updateOption', 'name': 'receive_access_hashes', 'value': {'@type': 'optionValueBoolean', 'value': True}}
> ```

Please look at the requests documentation, you are using an update to send a request.

**Comment by AYMENJD** [comment]
@cavallium where i can find "requests documentation" ?

**Comment by cavallium** [comment]
https://tdlight-team.github.io
