### ISSUE TITLE
I cant get SuperGroup

### ISSUE THREAD

**Issue by mateus-silvestre** [tdlight-team/tdlight#29]
I am receiving this error: ```Error { code = 400 message = "Invalid supergroup identifier" }``` on the code: ```TdApi.GetSupergroup getSupergroup = new TdApi.GetSupergroup(); getSupergroup.supergroupId = chatId; this.client.send(getSupergroup, re -> {```, the used id is correct...

**Comment by cavallium** [comment]
The id is not correct. Check your code

**Comment by mateus-silvestre** [comment]
the id is correct i'm sure. I am using this id: -1001516291509
