### ISSUE TITLE
I cant get supergroup

### ISSUE THREAD

**Issue by mateus-silvestre** [tdlight-team/tdlight#30]
I am receiving this error: ```Error { code = 400 message = "Invalid supergroup identifier" }``` on the code: TdApi.GetSupergroup getSupergroup = new ```TdApi.GetSupergroup(); getSupergroup.supergroupId = chatId; this.client.send(getSupergroup, re -> {```, the used id is correct... I am using this id: -1001516291509

**Comment by cavallium** [comment]
The id is wrong. chat id != supergroup id
