### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by dwap** [tdlight-team/tdlight#31]
Error :
`[ 70%] Building CXX object CMakeFiles/tdcore.dir/td/telegram/StickersManager.cpp.o
/home/v/tdlight/td/telegram/StickersManager.cpp:8858:112: error: member reference base type 'vector<td::StickerSetId> [3]' is not a structure or union
  output.push_back("\"featured_sticker_set_ids_\":"); output.push_back(std::to_string(featured_sticker_set_ids_.size()));
                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
1 error generated.
make[2]: *** [CMakeFiles/tdcore.dir/build.make:2260: CMakeFiles/tdcore.dir/td/telegram/StickersManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:464: CMakeFiles/tdcore.dir/all] Error 2
make: *** [Makefile:141: all] Error 2`
if change git repo to origin repo of td, then build is completed

**Comment by cavallium** [comment]
I'll fix it tomorrow, thanks
