### ISSUE TITLE
Please keep previous versions

### ISSUE THREAD

**Issue by AqlaSolutions** [tdlight-team/tdlight#37]
For an example I need tdlight version closest to d963044 tdlib commit version

**Comment by cavallium** [comment]
You can compile them, I don't delete any version

**Comment by AqlaSolutions** [comment]
Where are they? You rebase master branch, there are no other branches nor tags (except very old).

**Comment by cavallium** [comment]
Every time I rebase the master branch, I create a tag with the old version. They are all there.
