### ISSUE TITLE
Requested data is inaccessible for GetGroupsInCommon

### ISSUE THREAD

**Issue by spontanurlaub** [tdlight-team/tdlight#5]
`[ 3][t 0][1608283537.181689262][RequestActor.h:111][#4915906791530][!GetGroupsInCommonRequest]	Receive error for query: [Error : 500 : Requested data is inaccessible]`

**Comment by cavallium** [comment]
Does this method fail from a bot or an user?

**Comment by spontanurlaub** [comment]
Users, Bots aren't even allowed to call this method

**Comment by cavallium** [comment]
Let's see if with the next release it's fixed. I'll try it as soon as I can

**Comment by cavallium** [comment]
Is it fixed now?

**Comment by cavallium** [comment]
It should be fixed. closing.
