### ISSUE TITLE
Clean file_sources

### ISSUE THREAD

**Issue by cavallium** [tdlight-team/tdlight#6]
file_sources keeps growing.
Clean unused file_sources elements after memory_cleanup.

**Comment by andrew-ld** [comment]
https://www.youtube.com/watch?v=-ilXc0j1iHA

**Comment by andrew-ld** [comment]
fixed

**Comment by cavallium** [comment]
Now remote.id stays the same. Fixed.

**Comment by andrew-ld** [comment]
good
