### ISSUE TITLE
Loop in MessagesManager.cpp

### ISSUE THREAD

**Issue by andrew-ld** [tdlight-team/tdlight#8]
Find why tdlib goes into an infinite loop when postponing pts updates.

**Comment by MarcoBuster** [comment]
@andrew-ld Top quality issue

**Comment by cavallium** [comment]
The bug seems to be related to issue 1362 in the official repository

**Comment by andrew-ld** [comment]
fixed in https://github.com/tdlight-team/tdlight/commit/e0bcdab68ffb20eb43e628a29502558db47a6c97
